trigger:
- master

resources:
- repo: self

pool: Default

stages:
- stage: Build
  displayName: Build Stage
  jobs: 
  - job: BuildImage
    displayName: Build Docker Image
    steps:
    
    # Step 1: Docker build
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: glad2os/group-project
        Dockerfile: ./backend/Dockerfile
        tags: |
          $(Build.BuildId)
          latest

    # SonarQube analysis
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: $(SonarQubeServiceConnectionName)
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: $(SonarProjectKey)
        cliSources: 'backend'

    # Execute SonarQube analysis
    - task: SonarQubeAnalyze@4

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
