trigger:
- main

resources:
- repo: self

pool: Default

stages:

- stage: Build
  displayName: Build Stage
  jobs: 
  - job: BuildImage
    displayName: Build Docker Image
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: glad2os/group-project
        Dockerfile: ./backend/Dockerfile
        tags: |
          $(Build.BuildId)


    - script: echo "Placeholder for unit test step"
      displayName: Unit Tests
